### ISSUE TITLE
Add border rules for 600px 768px 992px and 1200px breakpoints

### ISSUE THREAD

**Issue by manuel12** [manuel12/fluent-css#10]

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start

**Comment by manuel12** [comment]
@Pulkitxm  I already assigned a couple tickets to you :) As soon as those are done I can assign you some more.

**Comment by manuel12** [comment]
Here you go :)

**Comment by manuel12** [comment]
Closing as done
