### ISSUE TITLE
Add padding rules for 600px 992px and 1200px breakpoints

### ISSUE THREAD

**Issue by manuel12** [manuel12/fluent-css#12]

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start

**Comment by manuel12** [comment]
@Pulkitxm  I already assigned a couple tickets to you :) As soon as those are done I can assign you some more.

**Comment by manuel12** [comment]
Here you go :) same principle as the others - please the add the classes to the 3 different breakpoints(600px/992px/1200px) with the appropriate prefixes.

Please don't hesitate to ask if you have any questions.

**Comment by manuel12** [comment]
Closing as done!
