### ISSUE TITLE
Have more consistent names for custom elements.

### ISSUE THREAD

**Issue by manuel12** [manuel12/fluent-css#4]

**Comment by Akash1965** [comment]
@manuel12 can i work on this issue? Would love to contribute

**Comment by manuel12** [comment]
@Akash1965 

Yes of course. In this issue all that needs to be done is to rename the css rules found src/custom-elements.css:

- .container-round to .round-container
- .heading-depth to .depth-heading
- .heading-round to .round-heading

Feel free ask if you have any questions :)
